// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btnBase': string;
  'flexContainer': string;
  'mainContainerBreak': string;
  'phoneBreak': string;
  'txtCentered': string;
  'underlineDotted': string;
  'whiteTxt': string;
  'yellowTxt': string;
}
export const cssExports: CssExports;
export default cssExports;
