// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'icon': string;
  'measurement': string;
  'phoneBreak': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
