// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'hidden': string;
  'pause': string;
  'play': string;
  'progress': string;
  'progressContainer': string;
  'progressPath': string;
  'timerBtn': string;
  'timerText': string;
  'visible': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
