// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon': string;
  'listItemContainer': string;
  'listSubContentContainer': string;
  'listSubContentWrapper': string;
  'mainContainerBreak': string;
  'methodIconContainer': string;
  'phoneBreak': string;
  'primaryListContent': string;
  'recipeText': string;
  'subContentIconContainer': string;
  'subContentText': string;
}
export const cssExports: CssExports;
export default cssExports;
