// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contentContainer': string;
  'headline': string;
  'mainContainerBreak': string;
  'phoneBreak': string;
  'prevBtn': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
