// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'headline': string;
  'icon': string;
  'iconContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
