// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'next': string;
  'prev': string;
}
export const cssExports: CssExports;
export default cssExports;
