// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btnContainer': string;
  'errorText': string;
}
export const cssExports: CssExports;
export default cssExports;
