// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'cupSelectorBtn': string;
  'cupSelectorContainer': string;
  'mainContainerBreak': string;
  'phoneBreak': string;
}
export const cssExports: CssExports;
export default cssExports;
