// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'input': string;
  'mainContainerBreak': string;
  'phoneBreak': string;
  'sliderContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
