// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'measurementValueText': string;
  'phoneBreak': string;
  'unitContainer': string;
  'unitTypeText': string;
  'valueContainer': string;
  'valuesContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
